### ISSUE TITLE
Loader will load endless resources in assembling machine

### ISSUE THREAD

**Issue by Fank** [Yousei9/Loader-Redux#1]
![image](https://user-images.githubusercontent.com/1900106/26953448-aeb89ce4-4caa-11e7-87ac-9cd7e2aa918f.png)

Current 1.8 mio transistors and it will continue loading them into the assembing machine.

Modlist:
```
~/.factorio/mods$ ls
AutoDeconstruct_0.1.8.zip  bobgreenhouse_0.15.2.zip  bobmining_0.15.2.zip   bobpower_0.15.3.zip             bobwarfare_0.15.3.zip        mod-settings.json
bobassembly_0.15.6.zip     bobinserters_0.15.1.zip   bobmodules_0.15.3.zip  bobrevamp_0.15.4.zip            Electric Furnaces_2.3.0.zip  Orbital Ion Cannon_1.5.1.zip
bobelectronics_0.15.2.zip  boblibrary_0.15.8.zip     bobores_0.15.6.zip     bobtech_0.15.3.zip              LoaderRedux_0.2.8.zip        Squeak Through_1.1.7.zip
bobenemies_0.15.2.zip      boblogistics_0.15.6.zip   bobplates_0.15.11.zip  bobvehicleequipment_0.15.2.zip  mod-list.json                WaterWell_1.0.18.zip

```

**Comment by Nexela** [comment]
Please upload the save and mods as zip, This is a base game issue probably with sleep/wake logic and beacons

**Comment by Fank** [comment]
[mods.zip](https://drive.google.com/open?id=0B89cS-w1YUV2OVBVR3QxMjg4dFU)
[savegame.zip](https://drive.google.com/open?id=0B89cS-w1YUV2QlhQTnY3a0ZLYm8)

**Comment by Yousei9** [comment]
There seems to be a bug in the base game with max buffer calculation.
Here's my test with green circuits. 
Without modules and beacons buffers to 144 iron 244 copper cables.
![2017-06-09-07-56-12-5667079](https://user-images.githubusercontent.com/8436934/26962969-2733a83c-4cea-11e7-9595-7ef9cd1063fe.jpg)

after boosting it to ridiculous +7000% the buffer only grew to 186 iron 469 copper cable
![2017-06-09-07-59-01-1063478](https://user-images.githubusercontent.com/8436934/26962987-40cafea8-4cea-11e7-83bf-17a6015aa1d7.jpg)

BUT when I remove the beacons so the assembler is holding more than its buffer allows it to it becomes a black hole.
![2017-06-09-08-06-20-8575001](https://user-images.githubusercontent.com/8436934/26963024-8eb77844-4cea-11e7-943d-67fca42007a1.jpg)

**Comment by Yousei9** [comment]
Update:
Until the devs update loader mechanics the only way to mend this bug is to read the input inventory of the assembler with Inventory Sensor and turn on feeding belts only while below a certain threshold like 500 units.

**Comment by ReikaKalseki** [comment]
Honestly I consider this desirable.

**Comment by Yousei9** [comment]
Why would assemblers storing infinite amounts of resources become desirable?
You can't access those items in any meaningful way.
It's unlikely assemblers in this state will ever be able to catch up and process the stored items.

The only real usage would be to use them as dump for unwanted items, which is done much better by void chests utilizing infinite chest prototype.

**Comment by ReikaKalseki** [comment]
Because in the cases where you are using loaders to feed assemblers, it is because you need a truly insane item throughput. Having larger in-assembler buffers help prevent any possible transient downtimes.

**Comment by Yousei9** [comment]
You still wouldn't need several million items in said assembler.
1-2 stacks are more than enough.

**Comment by ReikaKalseki** [comment]
I now realize I have misunderstood the discussion; I thought it was about the fact that loaders ignored the normal assembler recipe x2 loading behavior (like inserters do), not the complete lack of any limit.

**Comment by Hrecha** [comment]
it is necessary to swap the technology, but it turns out that the very last one is opened earlier than the last one
![image](https://user-images.githubusercontent.com/37973182/38171080-d2c968aa-359a-11e8-9b64-ed3d59c28b68.png)

**Comment by Yousei9** [comment]
Please report in a new issue if there is no existing matching yours.

**Comment by Yousei9** [comment]
Apperentlys this was fixed long ago and I never noticed.
