### ISSUE TITLE
Tech prerequisites for previous tiers should be added

### ISSUE THREAD

**Issue by Zaflis** [Yousei9/Loader-Redux#22]
Problem is that if you research logistics-2, you can research fast loader before the normal one. But you can't obviously craft it yet because tier 1 is required in recipe.

Currently tech prototype for fast loader looks like:
`prerequisites = {"logistics-2"},`
But it should be:
`prerequisites = {"logistics-2", "loader"},`
Also same for express loader:
`prerequisites = {"logistics-3", "fast-loader"},`
... and so on for bob's.

**Comment by Yousei9** [comment]
Duplicate of #7
