### ISSUE TITLE
Mod doesn't load with Bobsmods 0.16

### ISSUE THREAD

**Issue by foophoof** [Yousei9/Loader-Redux#23]
When launching the game on 0.16.36, I get this error:

```
Failed to load mods: Error in assignID, recipe with name 'green-loader' does not exist.

Source: green-loader (technology).

Mods to be disabled:
* LoaderRedux
* boblogistics
* omnimatter_science
```

It's not entirely clear to me if this is a bug in boblogistics or LoaderRedux, but it looks like the green-loader recipe is defined here?

**Comment by foophoof** [comment]
This is using LoaderRedux version 1.2.2, boblogistics 0.16.17, and omnimatter_science 0.5.0.

**Comment by petrukhnov** [comment]
Same problem without omni.

**Comment by petrukhnov** [comment]
boblogistics_0.16.15 also works

**Comment by Wherelock** [comment]
I just found out the reason. Basically, bob logistic just renamed their belt, from green transport belt to turbo transport belt and from purple transport belt to ultimate transport belt. what you need to do is updating the names of the green and purple ones in entity, item and recipe lua. It works for me.

**Comment by Wherelock** [comment]
![loader](https://user-images.githubusercontent.com/37926932/38131651-e4517f7a-33d5-11e8-9db0-4cacd56ff615.JPG)
and here's the bob logistics' in-game update log. it shows the belts' names have been changed.

**Comment by Yousei9** [comment]
I wish other mods would stop changing their item names for no reason.

**Comment by jinks** [comment]
Well, it's not *entirely* for no reason. Looking by the forum posts, bob is cleaning up, consolidating and re-organizing tiers in his mods for more consistency and maintainability.

**Comment by Yousei9** [comment]
There hardly ever is any reason to change the internal item names, unless you want to break every other mod trying to play nice with yours.

Anyways i fixed it for current bobsmods.
