### ISSUE TITLE
Request: blacklist for loader snapping

### ISSUE THREAD

**Issue by mspielberg** [Yousei9/Loader-Redux#30]
[Beltlayer](https://mods.factorio.com/mod/beltlayer) uses loaders for item transfer, and uses the on_player_rotated_entity event to keep different entities in sync. Unfortunately Loader Redux snapping changes the direction and type of the Beltlayer loaders, which causes some odd effects.

Here are some options that could help:

1) let me blacklist my Beltlayer loaders via a remote interface.
2) raise some sort of event that I can detect when a loader's configuration has been changed by snapping.

**Comment by Yousei9** [comment]
Whitelisting loader entities touched by loader redux seems like a better choice.
Only mods who want to use my code should need to register through remote interface.
