### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by ghost** [Yousei9/Loader-Redux#35]
Can I put a complete German translation of your mod into my mod to publishing it?

You don't have to worry about the German translation, because my mod has it then.

Please feel free to write me. Thank you.

**Comment by Yousei9** [comment]
Certainly, feel free to take that load off my shoulders.

**Comment by kingmax007** [comment]
Thank you.

I will contact you if my modification includes the translation of your mod.

Then you can link them.

**Comment by Yousei9** [comment]
Are we both talking about a mod consisting only of info.json and locale folder?
All a translation mod requires is an optional dependency in info.json for each mod it translates.

You don't need my permission nor any changes from my side to make a simple translation mod like that.

**Comment by kingmax007** [comment]
the info.json of the mods be the same, as youve uploaded it.... i translate only the locale-folder in german...

one mod, that translate all other mods with the localefiles....
