### ISSUE TITLE
Still no HR

### ISSUE THREAD

**Issue by Kamsta99** [Yousei9/Loader-Redux#40]
Let me fix this
[loaders.zip](https://github.com/Yousei9/Loader-Redux/files/2985412/loaders.zip)

**Comment by Yousei9** [comment]
Thanks,
Did you upscale those?

**Comment by Yousei9** [comment]
Can you clean up the white artifacts most noticeable on vertical blue and red loaders.

![2019-03-19-21-44-10-5224545](https://user-images.githubusercontent.com/8436934/54640691-af66b280-4a90-11e9-91e1-c19cef42c6e9.png)

**Comment by Kamsta99** [comment]
![hr-red-loader](https://user-images.githubusercontent.com/8656801/54644929-e4780280-4a9a-11e9-9ac2-7b3cab9e5b81.png)
![hr-express-loader](https://user-images.githubusercontent.com/8656801/54644930-e4780280-4a9a-11e9-9835-8de3c11b841c.png)
![hr-purple-loader](https://user-images.githubusercontent.com/8656801/54644931-e4780280-4a9a-11e9-88b7-237a32573753.png)
Should looks better
Yes its upscaled by AI but sometimes i need fix stuff like this myself :)

**Comment by Kamsta99** [comment]
If i have time i do better version

**Comment by Yousei9** [comment]
Thanks, those are less jarring.
I'll wait for your final version before publishing.

**Comment by Kamsta99** [comment]
![hr-express-loader](https://user-images.githubusercontent.com/8656801/54711904-3ed09c00-4b4b-11e9-8655-76ceb54314ab.png)
![hr-green-loader](https://user-images.githubusercontent.com/8656801/54711905-3f693280-4b4b-11e9-8c78-5a681918d810.png)
![hr-loader](https://user-images.githubusercontent.com/8656801/54711906-3f693280-4b4b-11e9-8d31-d8be387789ba.png)
![hr-purple-loader](https://user-images.githubusercontent.com/8656801/54711907-3f693280-4b4b-11e9-8cfa-adbbcd09e5e4.png)
![hr-red-loader](https://user-images.githubusercontent.com/8656801/54711908-4001c900-4b4b-11e9-964d-33a0e0aa693d.png)
