### ISSUE TITLE
Loaders won't load into/out train cars on 0.17.15

### ISSUE THREAD

**Issue by thrasherht** [Yousei9/Loader-Redux#41]
Testing the mod on a fresh map, and I am seeing that the loaders work with chests, but will not load or unload train cars. 

Tried with both multiplayer and single player.

**Comment by Yousei9** [comment]
Cargo Wagon interaction has been disabled by default for a while now as it's very script heavy.
It can be enabled in mod settings. The options are _none_, _automatic_  and _all_.
_Automatic_ will have some performance impact but should be playable on small maps.
All will have severe performance impact.

I recommend using stack inserter > chest > loader or miniloader instead.
