### ISSUE TITLE
0.17.23

### ISSUE THREAD

**Issue by cole4114** [Yousei9/Loader-Redux#43]
"Error in assignID, recipe with name 'purple-loader' does not exist"

**Comment by Yousei9** [comment]
At least attach factorio-current.log  in bug reports.

**Comment by cole4114** [comment]
[factorio-current.log](https://github.com/Yousei9/Loader-Redux/files/3027003/factorio-current.log)

**Comment by Yousei9** [comment]
A new version of boblogistics and he changed the tech yet again.
Thanks for the report.

**Comment by Yousei9** [comment]
Update:
Just tested against boblogistics 0.17.6, it works fine for me.

**Comment by cole4114** [comment]
I dont even have boblogistics

**Comment by cole4114** [comment]
I guess its a error in loader redux.

**Comment by Yousei9** [comment]
Ah, then some other mod adds logistics-4 and logistics-5 and LR tries inserting loaders that only exist with boblogistics in those.

**Comment by jimmyjon711** [comment]
FactorioExtended-Plus Transport has logistics-4 and logistics-5
