### ISSUE TITLE
Im BACK with new HR

### ISSUE THREAD

**Issue by Kamsta99** [Yousei9/Loader-Redux#44]
[entity.zip](https://github.com/Yousei9/Loader-Redux/files/3031901/entity.zip)

Now its should be better than before

**Comment by Yousei9** [comment]
Will this be your final edit?

**Comment by Yousei9** [comment]
These graphics have 2 problems:
- there are noticeable differences between in and out direction sprites
  especially express loader with a red spine shadows only in north out sprite
- colors have been changed
I very much preferred the colors from the previous version

**Comment by Kamsta99** [comment]
Sure so i fix this and reupload

**Comment by Kamsta99** [comment]
[hr-loader-final.zip](https://github.com/Yousei9/Loader-Redux/files/3038795/hr-loader-final.zip)
Done now its looks a lot better and use my color coding value same as in my mod ColorTIERHR

**Comment by Kamsta99** [comment]
It looks now that
![Factorio_2019_04_03_15_10_43_851](https://user-images.githubusercontent.com/8656801/55481922-b6aac600-5623-11e9-9c92-3c6147edfd0c.jpg)
