### ISSUE TITLE
Cannot join.

### ISSUE THREAD

**Issue by ChildishGiant** [Yousei9/Loader-Redux#45]
**Error message or bug description**
When joining a server I got this message.
![image](https://user-images.githubusercontent.com/13716824/58725267-9bb3c280-83d6-11e9-8b79-1ad8a9fcd2cd.png)

**Loader Redux version**
Both client and server were on 1.4.10

**Log file**
[factorio-current.log](https://github.com/Yousei9/Loader-Redux/files/3242545/factorio-current.log)

**Workaround**
The server restarting cleared this issue up for me

**Comment by Yousei9** [comment]
You have a lot of connectivity issues beside this error.
Its more likely this is a problem with your client, server or base Factorio than Loader Redux.

The way LR registers events has worked this way for 8 months now and this is the first time this error showed.

**Comment by ChildishGiant** [comment]
This was probably a one-off issue then. Thanks for clearing it up

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/59125006-088c0700-8959-11e9-89c2-a59005939f36.png)
Happened again and restarting the server again solved it. I doubt it's not related to this mod seeing as it happened twice and never without this mod. 
[factorio-current.log](https://github.com/Yousei9/Loader-Redux/files/3267150/factorio-current.log)

**Comment by Yousei9** [comment]
Seeing as there hasn't been any way of replicating the issue I consider it a faulty server.
