### ISSUE TITLE
Loader still in inventory after uninstalling

### ISSUE THREAD

**Issue by ThomasLachaux** [Yousei9/Loader-Redux#46]
Hi,

After uninstalling the mod (I didn't need it finally, sorrry ^^), I still have the loader visible. (View screenshot). Is there a way to get rid of them ?

![loader](https://user-images.githubusercontent.com/21559770/59213572-7d5b7d00-8bb5-11e9-81fd-e18e8cebbc30.png)

**Loader Redux version**
1.4.10
**Log file**
[factorio-current.log](https://github.com/Yousei9/Loader-Redux/files/3273082/factorio-current.log)

**Comment by Yousei9** [comment]
Loaders are base game items, just hidden.
Removing loader redux keeps loader recipes enabled until you manually remove them through console.
