### ISSUE TITLE
Seems to be a problem with This mod & IR 

### ISSUE THREAD

**Issue by EmuLegs** [Yousei9/Loader-Redux#47]
**Error message or bug description**
Im running a few mods, however when i try to add Loader Redulux, [Industrial Revolution throws an error](https://i.imgur.com/BSBwiHU.png)

I'm not 100% sure it's even your mod creating the problem, however it only happens when trying to add Loader Redulux

**To Reproduce**
seems the 2 mods work fine by there lonesome, but on added it to my mods it goops out / kills IR

*********************
Included is 
[the mod list im using](https://pastebin.com/NYjRBwqb), 
[A custom save 'BEFORE' adding Loader Redulux](https://github.com/Yousei9/Loader-Redux/files/3802282/Custom.Save.zip)
[An image of the error](https://i.imgur.com/BSBwiHU.png)
As well as [the Log file](https://pastebin.com/M48ZMVQ7)

**Comment by Yousei9** [comment]
Loader Redux only adds loader recipes to existing base technologies.
If other mods change the technology tree without porting ALL recipes in said technology that's hardly a fault in Loader Redux.
