### ISSUE TITLE
mod compatibility request

### ISSUE THREAD

**Issue by Lincolnmc** [Yousei9/Loader-Redux#48]
amazing mod, i would like to submit a request to you add compatibiliy for loaders of the higher tiers for factorioExtended Plus (https://mods.factorio.com/mod/FactorioExtended-Plus-Transport)

Thank you

**Comment by Yousei9** [comment]
1) this is not a bug but a feature request.

2) any mod can simply create loaders and register them with Loader Redux to have LR take care of snapping, train interaction asf.
