### ISSUE TITLE
Factorio Extended Plus intergration

### ISSUE THREAD

**Issue by billbo99** [Yousei9/Loader-Redux#49]
We have been asked to add support for  Loader-Redux to FE+by one of our users.
  https://github.com/jimmyjon711/FactorioExtended-Plus-Transport/issues/23

Can you please confirm that we need to create our own loader prototypes first,  then register them with your remote.call to have them added to a whitelist.

I only ask as "Deadlock loaders" had public API to create their loaders in the data phase.

**Comment by Yousei9** [comment]
Correct, you have to create item, entity and recipe in your mod.

You could call my make_loader_item and make_loader_entity functions, but I don't think they will help you as they mostly set graphics to my internal paths.

My API only takes care of loaders in control stage. 
Note, I had no time to test the new 1x1 loader prototype.

**Comment by billbo99** [comment]
thanks for the confirmation
