### ISSUE TITLE
Missing Filter

### ISSUE THREAD

**Issue by Byteme8bit** [Yousei9/Loader-Redux#5]
The filter for "High Speed Loader" (The green one - sorry not in game atm) is missing. :(

**Comment by Byteme8bit** [comment]
To be more specific, you cannot set filters for High Speed Loaders on inserters, loaders, [and I believe logistics requests](?)

**Comment by Byteme8bit** [comment]
I just realized this could be another mod's error and not yours. If that is the case my apologies for wasting your time :) I'm posting on the other suspect mod as well. Thanks!

**Comment by Yousei9** [comment]
You can't set filters for any loader operating in Belt > Chest direction. Doing so would only clog the belt.

Beside being pointless, mods couldn't even change this behavior.
