### ISSUE TITLE
Question: Adding compatibility with the Space Exploration mod

### ISSUE THREAD

**Issue by EldrinnElantey** [Yousei9/Loader-Redux#52]
The [Space Exploration](https://mods.factorio.com/mod/space-exploration) mod has a Space Transport Belt.
![image](https://user-images.githubusercontent.com/46845681/103525614-ee9a0980-4e98-11eb-8926-710ded771e24.png)
Is it possible to add a Loader of the same level with the appropriate parameters?

**Comment by Yousei9** [comment]
I won't add loaders for other mods myself.
All required data stage functions are public and for control stage there's an API to register loaders.

**Comment by EldrinnElantey** [comment]
> I won't add loaders for other mods myself.
> All required data stage functions are public and for control stage there's an API to register loaders.

I had the idea to try to do it myself, but I have absolutely no experience in this. Where can I read about modding on Factorio?

**Comment by Yousei9** [comment]
Sry for the late reply, I read it on my phone and flagged this as read making me loose track of this.

Either start with the [Wiki](https://wiki.factorio.com/Tutorial:Modding_tutorial/Gangsir) and/or just learn by reading code from base and mods.
