### ISSUE TITLE
Client Desync with Loaders Added by API

### ISSUE THREAD

**Issue by RobertPoston** [Yousei9/Loader-Redux#53]
**Error message or bug description**
I have been working on making a tiny mod that would add loaders that support Ultimate Belts. In singleplayer there are no issues, but on multiplayer/server anytime a loader added by the mod should snap to a container everyone except the host is desynced. My mod has the required calls to make the item and entity for the loader, recipes, and technology associated. Also the required control remote calls to the LR API in on_init and on_load.

**To Reproduce**
With a separate mod adding loaders for any other mod that adds belts, place a loader in a direction that would require snapping to a container, or change direction of feeding belts.

**Loader Redux version**
1.7.0

**Log file**
[factorio-current.log](https://github.com/Yousei9/Loader-Redux/files/8325233/factorio-current.log)

**Comment by Yousei9** [comment]
Please post your control.lua for reference.

**Comment by RobertPoston** [comment]
`script.on_init(function()
    remote.call("loader-redux", "add_loader", "ultra-fast-loader")
    remote.call("loader-redux", "add_loader", "extreme-fast-loader")
    remote.call("loader-redux", "add_loader", "ultra-express-loader")
    remote.call("loader-redux", "add_loader", "extreme-express-loader")
    remote.call("loader-redux", "add_loader", "ultimate-loader")
  end)


script.on_load(function()
  remote.call("loader-redux", "add_loader", "ultra-fast-loader")
  remote.call("loader-redux", "add_loader", "extreme-fast-loader")
  remote.call("loader-redux", "add_loader", "ultra-express-loader")
  remote.call("loader-redux", "add_loader", "extreme-express-loader")
  remote.call("loader-redux", "add_loader", "ultimate-loader")
end)`

[control.lua.txt](https://github.com/Yousei9/Loader-Redux/files/8326793/control.lua.txt)

The text is all that is in the file, but also the file is attached for reference

**Comment by Yousei9** [comment]
I think I found the problem.
My tables where local and called in on_load. 

Making them global and only called from on_init and on_configuration_changed "should" be MP save.

**Comment by RobertPoston** [comment]
I have downloaded the update and it no longer desyncs!

**Comment by Yousei9** [comment]
Good to hear.
