### ISSUE TITLE
Not working on Trains for Krastorio 2

### ISSUE THREAD

**Issue by mstruensee** [Yousei9/Loader-Redux#55]
Loader will not unload or load trains in Krastorio 2.  Not sure the issue, have tried multiple layouts and none seem to work?

I have a public server if you want to connect and see, can do a discord or something as well.

![image](https://user-images.githubusercontent.com/5142984/177405930-8e7b5144-67c6-4af2-8d45-c7dc629a0c5b.png)

Mods:
```
    {
      "name": "Krastorio2LoaderRedux",
      "enabled": true
    },
    {
      "name": "LoaderRedux",
      "enabled": true
    },
    {
      "name": "miniloader",
      "enabled": false
    },
    {
      "name": "vanilla-loaders-hd-krastorio",
      "enabled": true
    },
```

**Comment by Yousei9** [comment]
Krastorio2LoaderRedux needs to update to 1.8.0 API.
