### ISSUE TITLE
Use the wagon flag recently added to vanilla loaders

### ISSUE THREAD

**Issue by TacticalMook** [Yousei9/Loader-Redux#56]
In version 1.1.75, [Wube added a flag to vanilla loaders which lets them interact with wagons.](https://forums.factorio.com/viewtopic.php?p=579807#p579807) Refactoring the mod to use this feature should **considerably** improve its performance.

**Comment by Yousei9** [comment]
Thanks for the info.

Scripted train handling will be removed next release.
