### ISSUE TITLE
Shadows render on top of the loader sprite.

### ISSUE THREAD

**Issue by JackSPD** [Yousei9/Loader-Redux#57]
**Error message or bug description**
Shadows render on top of the loader sprite rather than under it. This issue was not present in the previous version of Loader Redux:

![2023-06-12 19_56_38-Window](https://github.com/Yousei9/Loader-Redux/assets/55201566/cb27af81-cf5a-4eaf-aa1c-21064fd4c33c)

**To Reproduce**
Place any loader

**Loader Redux version**
1.9.0

**Comment by Yousei9** [comment]
Thanks for reporting.

I removed the layer information alongside 0.17 animations.
Fixed in 1.9.1.
