### ISSUE TITLE
Near belt splitters stop working in factorio 0.16

### ISSUE THREAD

**Issue by razbezhkin** [Yousei9/Loader-Redux#6]
Some belt splitters stop send goods near loader.
factorio 0.16.4
loader redux 1.2.0
![factorioerror](https://user-images.githubusercontent.com/26468460/34082076-7cde410e-e379-11e7-8623-d2df5bd280ec.PNG)

**Comment by razbezhkin** [comment]
this situation corrected by twice change direction of loader (by press 'R' key on loader)

**Comment by Yousei9** [comment]
Unless this is a direct result of loader snapping freaking out you'd have to report this to the factorio dev team.
Loaders are a hidden item from the base game. Loader Redux only makes it available with some polish.

**Comment by Nexela** [comment]
This *might* be related to loader snapping.   To confirm we would need a save that has this problem so we can check if item is on the belt or on the ground.

**Comment by Yousei9** [comment]
I presume it's related to https://forums.factorio.com/viewtopic.php?f=7&t=55055
So it should have been fixed in 0.16.13.

I'll close this issue for now.
