### ISSUE TITLE
Loader research

### ISSUE THREAD

**Issue by Jelmergu** [Yousei9/Loader-Redux#7]
As it is now you can research 'Fast loader'(red) before you researched 'Loader'(yellow). But as the fast loader requires the yellow loader in the crafting recipe, it would make more sense to have the loader research as a requirement for the fast loader research

**Comment by Yousei9** [comment]
> Just because you can research something doesn't mean you can build it.

That's the stance of the base game I also adhere to in my mods. 

Keeping implicit requirements out of the research tree keeps it from becoming an unholy mess of lines between techs.

**Comment by Jelmergu** [comment]
>> Just because you can research something doesn't mean you can build it.
>
>That's the stance of the base game I also adhere to in my mods.

That is understandable, however the base game doesn't adhere to it. Take 'Advanced material processing 2'(unlocks purple science and electric furnace). It is locked behind 'Advanced electronics'(unlocks red ciruit and blue science). It is logical that AMP2 is locked behind AE, it requires red circuits to be build. 
It is the same with the belts(the category where the loader belongs to) yellow is required for red which is required for blue, it only makes sense that it is the same for loaders.

> Keeping implicit requirements out of the research tree keeps it from becoming an unholy mess of lines between techs.
Which is understandable for big researches that might be found in Bob's mods or Angels, but with this change the tech tree would look like the pic below, which is not a big mess of lines
![not such a big mess](https://user-images.githubusercontent.com/18192158/34382461-5a5fb25a-eb0f-11e7-9fd5-a029dae37c71.png)
