### ISSUE TITLE
Color Correction

### ISSUE THREAD

**Issue by Incvisitor** [Yousei9/Loader-Redux#8]
I made some color correction for your mod. 
https://cdn1.savepice.ru/uploads/2018/1/2/58a8be73630ec31a2f315142cfd853b9-full.png
How do you like these colors?
Link on archive with color correction:
https://www.dropbox.com/s/i8r8ksu4gd2u5uv/ColorCorrection.zip?dl=0

**Comment by Yousei9** [comment]
I think they lost too much shadow and plasticity while the colors are still too saturated to match the vanilla items..
Your blue and red are certainly a step in the right direction.
The original yellow colors fits pretty well.
Did you even change green and purple for boblogistics?

**Comment by Incvisitor** [comment]
Perhaps they are lost in shadows and plasticity, perhaps. The colors are also a bit bright and juicy. The new yellow is closer to vanilla than the last, that's for sure. For Bob logistics, I did not change anything, because I do not play this mod and I do not know how different colors there are.

I think to remodel the loader itself, closer to the original style. If it works, I'll show)

**Comment by Incvisitor** [comment]
n general, I could not make a beautiful analog bootloader, so I decided to improve the color correction. This time, even the color became more acceptable and the shadows were preserved.
https://www.dropbox.com/s/nq2cvixppux890b/ColorCorrection2.zip?dl=0
https://cdn1.savepice.ru/uploads/2018/1/3/299f5d1e5098b047e5b0b7e8086a7a3e-full.png

**Comment by Yousei9** [comment]
Version2 colors fit really well with the base entities.
![2018-01-03-17-13-44-8323323](https://user-images.githubusercontent.com/8436934/34528625-bac725de-f0a9-11e7-8379-83afca0e8233.jpg)

There already is a mod using graphics more in line with the base game, but I prefer the models Archangel designed.

Sidenote: You can upload files into posts on github.

**Comment by Incvisitor** [comment]
I added a color correction for Bob mods. It looks good.
![2_1](https://user-images.githubusercontent.com/18414913/34550078-891c9fb8-f140-11e7-86fc-2a1c91162c5f.png)
[ColorCorrection3.zip](https://github.com/Yousei9/Loader-Redux/files/1602404/ColorCorrection3.zip)

If you can, then give the Archangel the thought of detailing. Now its loaders look too new, compared to the splitters and underground belts of Vanilla and Bob. Can it be worth adding more details, or scratches and rust?
![2_1 copy](https://user-images.githubusercontent.com/18414913/34550140-fda6eb68-f140-11e7-92ea-04e122ee64fe.png)

**Comment by Yousei9** [comment]
I was about to say scratches would make them look even better.

It's really annoying clicking through one pull request per file, next time fork the development branch and create one pull request when you are done with all changes.

**Comment by Incvisitor** [comment]
Forgive me for this. I have not worked with github before.
So I probably did a lot of unnecessary work. True, I think color correction can be considered complete, there will not be a new kind of loaders with scratches and rust.
